#!/bin/bash
# rank-variants.sh - Analyzes match results, ranks variants, and promotes winner
#
# Usage: ./scripts/rank-variants.sh <bot> <opponent> <map> [num_champions]
#
# Scoring:
#   Win in ≤1500 rounds: SCORE = 20000 - rounds (goal met - pure speed)
#   Win in >1500 rounds: SCORE = 10000 - rounds + (enemy_kills * 50) + (victory_points * 2.5) + (bullets_generated / 100)
#   Loss (or win >=2999): SCORE = 10000 - rounds + (enemy_kills * 50) + (victory_points * 2.5) + (bullets_generated / 100) - 5000
#
# Scores are aggregated across all opponents (main + champions).
# Goal check is based on the primary opponent match only.
#
# Output: src/<bot>/.state/variant-results.json
# Action: Promotes winning variant to original if it scores higher, saves champion

set -e

BOT="${1:-}"
OPPONENT="${2:-}"
MAP="${3:-MagicWood}"
NUM_CHAMPIONS="${4:-0}"
NUM_VARIANTS=10

if [[ -z "$BOT" || -z "$OPPONENT" ]]; then
    echo "Usage: $0 <bot> <opponent> [map] [num_champions]"
    exit 1
fi

STATE_DIR="src/$BOT/.state"
MATCHES_DIR="matches"
RESULTS_FILE="$STATE_DIR/variant-results.json"

mkdir -p "$STATE_DIR"

echo "Analyzing match results..."
echo ""

# Python script to analyze matches using database files
python3 << 'PYEOF' - "$BOT" "$OPPONENT" "$MAP" "$NUM_VARIANTS" "$MATCHES_DIR" "$RESULTS_FILE" "$NUM_CHAMPIONS"
import sys
import json
import os
import sqlite3

bot = sys.argv[1]
opponent = sys.argv[2]
map_name = sys.argv[3]
num_variants = int(sys.argv[4])
matches_dir = sys.argv[5]
results_file = sys.argv[6]
num_champions = int(sys.argv[7])

# Build opponent labels list
opponent_labels = ['opponent']
for c in range(num_champions):
    opponent_labels.append(f'champ{c}')


def analyze_match(match_name):
    """Analyze a match from its database file."""
    db_file = os.path.join(matches_dir, f"{match_name}.db")
    log_file = os.path.join(matches_dir, f"{match_name}.log")

    result = {
        'won': False,
        'rounds': 3000,
        'enemy_kills': 0,
        'bullets_generated': 0,
        'victory_points': 0,
        'parsed': False,
        'source': 'none'
    }

    # Try database first (most reliable)
    if os.path.exists(db_file):
        try:
            conn = sqlite3.connect(db_file)
            conn.row_factory = sqlite3.Row

            # Get winner
            winner_row = conn.execute(
                "SELECT value FROM metadata WHERE key='winner'"
            ).fetchone()
            winner = winner_row['value'] if winner_row else None

            # Get total rounds
            rounds_row = conn.execute(
                "SELECT MAX(round_id) as max_round FROM rounds"
            ).fetchone()
            total_rounds = rounds_row['max_round'] if rounds_row and rounds_row['max_round'] else 3000

            # Get enemy kills (Team A killed Team B units)
            try:
                kills_row = conn.execute("""
                    SELECT COUNT(*) as kills FROM events
                    WHERE event_type='death' AND team='B'
                    AND body_type NOT IN ('TREE_BULLET', 'TREE_NEUTRAL', 'BULLET', 'NONE')
                """).fetchone()
                result['enemy_kills'] = kills_row['kills'] if kills_row else 0
            except:
                result['enemy_kills'] = 0

            # Get total bullets generated by Team A
            try:
                bullets_row = conn.execute("""
                    SELECT COALESCE(SUM(team_a_bullets_generated), 0) as total
                    FROM snapshots
                """).fetchone()
                result['bullets_generated'] = int(bullets_row['total']) if bullets_row else 0
            except:
                result['bullets_generated'] = 0

            # Get Team A victory points
            try:
                vp_row = conn.execute("""
                    SELECT COALESCE(MAX(team_a_victory_points), 0) as vp
                    FROM snapshots
                """).fetchone()
                result['victory_points'] = int(vp_row['vp']) if vp_row else 0
            except:
                result['victory_points'] = 0

            conn.close()

            if winner:
                result['won'] = (winner == 'A')
                result['rounds'] = int(total_rounds)
                result['parsed'] = True
                result['source'] = 'database'
                return result
        except Exception as e:
            pass

    # Fallback: parse log file
    if os.path.exists(log_file):
        try:
            with open(log_file, 'r') as f:
                content = f.read()

            # Look for winner patterns
            if 'winner=A' in content or 'Team A wins' in content:
                result['won'] = True
                result['parsed'] = True
                result['source'] = 'log'
            elif 'winner=B' in content or 'Team B wins' in content:
                result['won'] = False
                result['parsed'] = True
                result['source'] = 'log'

            # Look for round count
            import re
            for line in content.split('\n'):
                # Match patterns like "Round 1234" or "rounds: 1234"
                round_match = re.search(r'round[s]?\s*[:#=]?\s*(\d+)', line, re.IGNORECASE)
                if round_match:
                    r = int(round_match.group(1))
                    if 1 <= r <= 3000:
                        result['rounds'] = max(result['rounds'], r) if result['rounds'] < 3000 else r
        except Exception:
            pass

    return result


def calculate_score(won, rounds, enemy_kills=0, bullets_generated=0, victory_points=0):
    """Calculate score for ranking.

    Scoring:
      Win in ≤1500 rounds: 20000 - rounds (goal met - pure speed)
      Win in >1500 rounds: 10000 - rounds + bonuses
      Loss (or win >=2999): 10000 - rounds + bonuses - 5000
    """
    if won and rounds <= 1500:
        # Goal met - pure round optimization
        return 20000 - rounds
    else:
        # All other cases - reward kills, economy, and victory points
        kill_bonus = enemy_kills * 50
        econ_bonus = int(bullets_generated / 100)
        vp_bonus = int(victory_points * 2.5)
        base_score = 10000 - rounds + kill_bonus + econ_bonus + vp_bonus
        # Penalty for losing (or barely winning at >=2999 rounds)
        if not won or rounds >= 2999:
            base_score -= 5000
        return base_score


# Collect results - aggregate scores across all opponents
competitors = ['original'] + [f'v{v}' for v in range(1, num_variants + 1)]
results = []

for comp in competitors:
    # Build match name prefix
    if comp == 'original':
        match_prefix = f"{bot}_original"
    else:
        match_prefix = f"{bot}_{comp}"

    total_score = 0
    matches = []
    primary_won = False
    primary_rounds = 3000
    has_any_match = False

    for label in opponent_labels:
        match_name = f"{match_prefix}_vs_{label}"
        match_result = analyze_match(match_name)

        if not match_result['parsed'] and not os.path.exists(os.path.join(matches_dir, f"{match_name}.db")):
            # Skip variants that don't exist
            if comp != 'original':
                continue

        score = calculate_score(
            match_result['won'],
            match_result['rounds'],
            match_result['enemy_kills'],
            match_result['bullets_generated'],
            match_result['victory_points']
        )
        total_score += score
        has_any_match = True

        match_entry = {
            'opponent_label': label,
            'won': match_result['won'],
            'rounds': match_result['rounds'],
            'enemy_kills': match_result['enemy_kills'],
            'bullets_generated': match_result['bullets_generated'],
            'victory_points': match_result['victory_points'],
            'score': score,
            'source': match_result['source']
        }
        matches.append(match_entry)

        # Track primary opponent result for goal check
        if label == 'opponent':
            primary_won = match_result['won']
            primary_rounds = match_result['rounds']

    if has_any_match:
        results.append({
            'name': comp,
            'total_score': total_score,
            'primary_won': primary_won,
            'primary_rounds': primary_rounds,
            'match_count': len(matches),
            'matches': matches
        })

# Sort by total_score descending
results.sort(key=lambda x: x['total_score'], reverse=True)

# Determine winner and goal status
if not results:
    print("ERROR: No match results found!")
    sys.exit(1)

winner = results[0]['name']
winner_score = results[0]['total_score']
winner_primary_won = results[0]['primary_won']
winner_primary_rounds = results[0]['primary_rounds']

# Goal check based on primary opponent only
goal_met = 'YES' if (winner_primary_won and winner_primary_rounds <= 1500) else 'NO'

# Check if winner beats original
original_result = next((r for r in results if r['name'] == 'original'), None)
original_score = original_result['total_score'] if original_result else -9999

should_promote = (winner != 'original' and winner_score > original_score)

# Output
output = {
    'winner': winner,
    'winner_score': winner_score,
    'winner_won': winner_primary_won,
    'winner_rounds': winner_primary_rounds,
    'goal_met': goal_met,
    'should_promote': should_promote,
    'original_score': original_score,
    'num_opponents': len(opponent_labels),
    'results': results
}

with open(results_file, 'w') as f:
    json.dump(output, f, indent=2)

# Print table
print("=" * 90)
print("RESULTS TABLE")
print("=" * 90)
print("")

if num_champions > 0:
    print(f"Opponents: {opponent} + {num_champions} champion(s) ({len(opponent_labels)} total)")
    print("")

# Header
print(f"{'Variant':<10} {'Total':<8} {'Matches':<8} ", end="")
for label in opponent_labels:
    print(f"{label:<30} ", end="")
print()
print("-" * (26 + 31 * len(opponent_labels)))

for r in results:
    print(f"{r['name']:<10} {r['total_score']:<8} {r['match_count']:<8} ", end="")
    # Per-opponent breakdown
    match_by_label = {m['opponent_label']: m for m in r['matches']}
    for label in opponent_labels:
        m = match_by_label.get(label)
        if m:
            won_str = "W" if m['won'] else "L"
            kills = m.get('enemy_kills', 0)
            vp = m.get('victory_points', 0)
            print(f"{won_str} {m['rounds']}r {kills}k {vp}vp {m['score']:<6} ", end="")
        else:
            print(f"{'--':<30} ", end="")
    print()

print("")
print("=" * 90)
print(f"WINNER: {winner} (Aggregate Score: {winner_score})")
print(f"GOAL MET: {goal_met} (based on primary opponent match)")
if should_promote:
    print(f"ACTION: PROMOTE {winner} -> original (score {winner_score} > {original_score})")
else:
    print(f"ACTION: Keep original (best or tied)")
print("")
print("Scoring formula (per matchup):")
print("  Win ≤1500 rounds:  20000 - rounds")
print("  Win >1500 rounds:  10000 - rounds + (kills*50) + (vp*2.5) + (bullets/100)")
print("  Loss/win >=2999:   10000 - rounds + (kills*50) + (vp*2.5) + (bullets/100) - 5000")
print("  Aggregate = sum of all matchup scores")
print("=" * 90)

PYEOF

echo ""
echo "Results saved to: $RESULTS_FILE"

# ═══════════════════════════════════════════════════════════════════════════════
# PROMOTE WINNER IF APPLICABLE
# ═══════════════════════════════════════════════════════════════════════════════

SHOULD_PROMOTE=$(python3 -c "
import json
with open('$RESULTS_FILE', 'r') as f:
    data = json.load(f)
print('YES' if data.get('should_promote', False) else 'NO')
")

WINNER=$(python3 -c "
import json
with open('$RESULTS_FILE', 'r') as f:
    data = json.load(f)
print(data.get('winner', 'original'))
")

if [[ "$SHOULD_PROMOTE" == "YES" && "$WINNER" != "original" ]]; then
    echo ""
    echo "Promoting $WINNER to original..."

    WINNER_DIR="src/${BOT}_${WINNER}"
    if [[ ! -d "$WINNER_DIR" ]]; then
        echo "Error: Winner folder not found: $WINNER_DIR"
        exit 1
    fi

    # Backup state directory
    if [[ -d "$STATE_DIR" ]]; then
        mv "$STATE_DIR" "/tmp/${BOT}_state_backup_$$"
    fi

    # Copy winner Java files to original (excluding .state)
    for java_file in "$WINNER_DIR"/*.java; do
        if [[ -f "$java_file" ]]; then
            filename=$(basename "$java_file")
            # Update package declaration back to original
            sed "s/^package ${BOT}_${WINNER};/package ${BOT};/" "$java_file" > "src/$BOT/$filename"
        fi
    done

    # Restore state directory
    if [[ -d "/tmp/${BOT}_state_backup_$$" ]]; then
        mv "/tmp/${BOT}_state_backup_$$" "$STATE_DIR"
    fi

    echo "✓ Promoted $WINNER to $BOT"

    # Save champion: copy promoted original to champion folder
    CHAMPION_DIR="src/${BOT}_champion_${NUM_CHAMPIONS}"
    echo "Saving champion as ${BOT}_champion_${NUM_CHAMPIONS}..."
    mkdir -p "$CHAMPION_DIR"
    for java_file in "src/$BOT"/*.java; do
        if [[ -f "$java_file" ]]; then
            filename=$(basename "$java_file")
            # Update package declaration to champion package name
            sed "s/^package ${BOT};/package ${BOT}_champion_${NUM_CHAMPIONS};/" "$java_file" > "$CHAMPION_DIR/$filename"
        fi
    done
    # Fix internal references to the package
    for java_file in "$CHAMPION_DIR"/*.java; do
        if [[ -f "$java_file" ]]; then
            sed -i.bak "s/import ${BOT}\./import ${BOT}_champion_${NUM_CHAMPIONS}./g" "$java_file"
            rm -f "${java_file}.bak"
        fi
    done
    echo "✓ Champion saved to $CHAMPION_DIR"


else
    echo ""
    echo "No promotion needed (original is best or tied)"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# CLEANUP
# ═══════════════════════════════════════════════════════════════════════════════

echo ""
echo "Cleaning up variant folders and match files..."

for v in $(seq 1 $NUM_VARIANTS); do
    if [[ -d "src/${BOT}_v${v}" ]]; then
        rm -rf "src/${BOT}_v${v}"
    fi
done

rm -f "$MATCHES_DIR"/${BOT}*.bc17 2>/dev/null || true
rm -f "$MATCHES_DIR"/${BOT}*.db 2>/dev/null || true
rm -f "$MATCHES_DIR"/${BOT}*.log 2>/dev/null || true

echo "✓ Cleanup complete"
